# Spring server
server.port=8085

# Enable compression
server.compression.enabled=true
server.compression.mime-types=image/png,image/jpeg,image/gif

# Increase buffer sizes
server.tomcat.max-http-post-size=10MB

# Postgres
spring.datasource.url=jdbc:postgresql://localhost/scribe-ref-db
spring.datasource.username=postgres
spring.datasource.password=postgres

scribe-ref.arquivo.scribe-rest.embedding-service-url=http://localhost:8000/embed



