# Spring server
server.port=8085

# Enable compression
server.compression.enabled=true
server.compression.mime-types=image/png,image/jpeg,image/gif
server.forward-headers-strategy=native

# Increase buffer sizes
server.tomcat.max-http-post-size=10MB

# Postgres
spring.datasource.url=jdbc:postgresql://localhost/scribe-ref-db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

scribe-ref.arquivo.scribe-rest.embedding-service-url=http://localhost:8000/embed
scribe-ref.images.base-path=${IMAGES_BASE_PATH:../images}


# OpenIA API key
scribe-ref.arquivo.scribe-news-rest.open-ai.api-key=${OPEN_IA_API_KEY}
scribe-ref.arquivo.scribe-news-rest.open-ia.max-usage=${OPEN_IA_MAX_USAGE}
scribe-ref.arquivo.scribe-news-rest.open-ia.max-usage-period=${OPEN_IA_MAX_USAGE_PERIOD}

# Google OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri=${GOOGLE_REDIRECT_URI}
app.frontend-url=${FRONTEND_URL}


# Session cookie settings for cross-origin
server.servlet.session.cookie.same-site=lax
server.servlet.session.cookie.secure=true
# Optional but recommended: share session across www and non-www
server.servlet.session.cookie.domain=press-digger.com

# Session persistence
server.servlet.session.timeout=24h
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.max-age=86400
server.servlet.session.persistent=true
server.error.include-message=always