# Spring server
server.port=8085

# Postgres
spring.datasource.url=jdbc:postgresql://localhost/scribe-ref-db
spring.datasource.username=postgres
spring.datasource.password=postgres

scribe-ref.arquivo.scribe-rest.embedding-service-url=http://localhost:8000/embed
