#!/bin/sh

set -e

# Add system user
# $1 = user
# $2 = uid
# $3 = group
# $4 = description
# $5 = shell (defaults to /bin/false)
addUser() {
    user="$1"
    if [ -z "$user" ]; then
        echo "usage: addUser user [group] [description] [shell]"
        exit 1
    fi
    uid="$2"
    if [ -z "$uid" ]; then
        uid_flags=""
    else
        uid_flags="--uid $uid"
    fi
    group=${3:-$user}
    descr=${4:-No description}
    shell=${5:-/bin/false}
    if ! getent passwd | grep -q "^$user:"; then
        echo "Creating system user: $user in group $group"
        useradd $uid_flags --gid $group -r --shell $shell -c "$descr" $user
    fi
}

# Add system group
# $1 = group
# $2 = gid
addGroup() {
    group="$1"
    gid="$2"
    if [ -z "$gid" ]; then
        gid_flags=""
    else
        gid_flags="--gid $gid"
    fi
    if ! getent group | grep -q "^$group:"; then
        echo "Creating system group: $group"
        groupadd $gid_flags -r $group
    fi
}


# #######################################


addGroup arquivo ""
addUser arquivo "" arquivo "ScribeRef application account" /bin/false
