############################################################################
############################################################################
# Auxiliary services definitions
#
# This is not meant to be run directly, but to be used as base definitions
# referenced from other docker compose files (with 'extends' clause).
############################################################################
services:

  embedding-service:
    build: ./embedding-service
    container_name: embedding-service
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          memory: 1g