# Spring server
server.port=8083

# Postgres
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost/scribe-ref-db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

#Kafka
#Kafka consumer
spring.kafka.consumer.group-id=arquivo-text-processor-1
spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.listener.ack-mode=manual
spring.kafka.listener.concurrency=1
spring.kafka.consumer.properties.partition.assignment.strategy=org.apache.kafka.clients.consumer.RoundRobinAssignor
spring.kafka.consumer.max-poll-interval-ms=900000
spring.kafka.consumer.max-poll-records=3
spring.kafka.consumer.session-timeout-ms=45000
spring.kafka.consumer.heartbeat-interval-ms=15000

## topic to send
scribe-ref.arquivo.scribe-news-text-processor.kafka.to-listen.topic=${TEXT_PROCESSOR_TOPIC}
# increased concurrency to allow parallel processing (tune based on CPU/network)
scribe-ref.arquivo.scribe-news-text-processor.kafka.to-listen.concurrency=${TEXT_PROCESSOR_CONCURRENCY}

scribe-ref.arquivo.scribe-news-text-processor.kafka.to-send.topic=${EMBEDDING_PROCESSOR_TOPIC}
scribe-ref.arquivo.scribe-news-text-processor.kafka.to-send.concurrency=${EMBEDDING_PROCESSOR_CONCURRENCY}

# Service properties
scribe-ref.arquivo.scribe-news-text-processor.enable=true

# OpenIA API key
scribe-ref.arquivo.scribe-news-text-processor.open-ai.api-key=${OPEN_IA_API_KEY}


scribe-ref.arquivo.scribe-news-text-processor.author-extractor-url=http://localhost:8003/extract-persons
