insert into keyword (name) values ('PS');
insert into keyword (name) values ('PSD');
insert into keyword (name) values ('BE');
insert into keyword (name) values ('PCP');
insert into keyword (name) values ('CDS');
insert into keyword (name) values ('Verdes');
insert into keyword (name) values ('Chega');
insert into keyword (name) values ('IL');
insert into keyword (name) values ('Livre');
insert into keyword (name) values ('PAN');
insert into keyword (name) values ('Juventude Socialista');
insert into keyword (name) values ('Juventude Comunista');
insert into keyword (name) values ('Juventude Popular');
insert into keyword (name) values ('António Costa');
insert into keyword (name) values ('Marcelo Rebelo de Sousa');
insert into keyword (name) values ('Rui Rio');
insert into keyword (name) values ('Catarina Martins');
insert into keyword (name) values ('Jerónimo de Sousa');
insert into keyword (name) values ('Assunção Cristas');
insert into keyword (name) values ('André Ventura');
insert into keyword (name) values ('Rui Tavares');
insert into keyword (name) values ('João Ferreira');
insert into keyword (name) values ('Mariana Mortágua');
insert into keyword (name) values ('Pedro Nuno Santos');
insert into keyword (name) values ('João Leão');
insert into keyword (name) values ('Mário Centeno');
insert into keyword (name) values ('Eduardo Cabrita');
insert into keyword (name) values ('Marta Temido');
insert into keyword (name) values ('Tiago Brandão Rodrigues');
insert into keyword (name) values ('Graça Fonseca');
insert into keyword (name) values ('Augusto Santos Silva');
insert into keyword (name) values ('Fernando Medina');
insert into keyword (name) values ('João Galamba');
insert into keyword (name) values ('Pedro Adão e Silva');
insert into keyword (name) values ('Mariana Vieira da Silva');
insert into keyword (name) values ('José Luís Carneiro');
insert into keyword (name) values ('Lisboa');
insert into keyword (name) values ('Porto');
insert into keyword (name) values ('Portugal');
insert into keyword (name) values ('Algarve');
insert into keyword (name) values ('Madeira');
insert into keyword (name) values ('Açores');
insert into keyword (name) values ('Governo');
insert into keyword (name) values ('Assembleia da República');
insert into keyword (name) values ('Parlamento');
insert into keyword (name) values ('Ministério da Justiça');
insert into keyword (name) values ('Ministério da Educação');
insert into keyword (name) values ('Ministério da Saúde');
insert into keyword (name) values ('Ministério da Economia');
insert into keyword (name) values ('Ministério da Cultura');
insert into keyword (name) values ('Ministério da Agricultura');
insert into keyword (name) values ('Ministério da Defesa');
insert into keyword (name) values ('Ministério do Trabalho');
insert into keyword (name) values ('Ministério da Administração Interna');
insert into keyword (name) values ('Política');
insert into keyword (name) values ('Economia');
insert into keyword (name) values ('Justiça');
insert into keyword (name) values ('Saúde');
insert into keyword (name) values ('Educação');
insert into keyword (name) values ('Cultura');
insert into keyword (name) values ('Ciência');
insert into keyword (name) values ('Tecnologia');
insert into keyword (name) values ('Ambiente');
insert into keyword (name) values ('Desporto');
insert into keyword (name) values ('Futebol');
insert into keyword (name) values ('Emprego');
insert into keyword (name) values ('Trabalho');
insert into keyword (name) values ('Desemprego');
insert into keyword (name) values ('Direitos Humanos');
insert into keyword (name) values ('Inclusão');
insert into keyword (name) values ('Cidadania');
insert into keyword (name) values ('Liberdade de Expressão');
insert into keyword (name) values ('Jornalismo');
insert into keyword (name) values ('Imprensa');
insert into keyword (name) values ('Redes Sociais');
insert into keyword (name) values ('Internet');
insert into keyword (name) values ('Cibersegurança');
insert into keyword (name) values ('Privacidade');
insert into keyword (name) values ('Inteligência Artificial');
insert into keyword (name) values ('Big Data');
insert into keyword (name) values ('Blockchain');
insert into keyword (name) values ('Criptomoedas');
insert into keyword (name) values ('Startups');
insert into keyword (name) values ('Investimento');
insert into keyword (name) values ('Orçamento de Estado');
insert into keyword (name) values ('Impostos');
insert into keyword (name) values ('Subsídios');
insert into keyword (name) values ('Reformas');
insert into keyword (name) values ('Eleições Legislativas');
insert into keyword (name) values ('Eleições Presidenciais');
insert into keyword (name) values ('Eleições Autárquicas');
insert into keyword (name) values ('Referendos');
insert into keyword (name) values ('Feriados Nacionais');
insert into keyword (name) values ('Comemorações');
insert into keyword (name) values ('Festivais');
insert into keyword (name) values ('Protestos');
insert into keyword (name) values ('Greves');
insert into keyword (name) values ('Manifestação');
insert into keyword (name) values ('Crime');
insert into keyword (name) values ('Polícia');
insert into keyword (name) values ('Segurança');
insert into keyword (name) values ('Violência');
insert into keyword (name) values ('Justiça Criminal');
insert into keyword (name) values ('Sindicato');
insert into keyword (name) values ('Negociações');
insert into keyword (name) values ('Conflitos');
insert into keyword (name) values ('Corrupção');
insert into keyword (name) values ('Investigação');
insert into keyword (name) values ('Tribunal');
insert into keyword (name) values ('Juiz');
insert into keyword (name) values ('Advogado');
insert into keyword (name) values ('Processo');
insert into keyword (name) values ('Detenção');
insert into keyword (name) values ('Prisão');
insert into keyword (name) values ('Cidadão');
insert into keyword (name) values ('Município');
insert into keyword (name) values ('Câmara Municipal');
insert into keyword (name) values ('Autarquia');
insert into keyword (name) values ('Educação Básica');
insert into keyword (name) values ('Ensino Secundário');
insert into keyword (name) values ('Universidade');
insert into keyword (name) values ('Ciência Política');
insert into keyword (name) values ('Geopolítica');
insert into keyword (name) values ('História');
insert into keyword (name) values ('Economia Social');
insert into keyword (name) values ('Finanças Públicas');
insert into keyword (name) values ('Investimento Estrangeiro');
insert into keyword (name) values ('Startups Tecnológicas');
insert into keyword (name) values ('Inovação');
insert into keyword (name) values ('Empreendedorismo');
insert into keyword (name) values ('Turismo');
insert into keyword (name) values ('Cultura Popular');
insert into keyword (name) values ('Artes Plásticas');
insert into keyword (name) values ('Artes Performativas');
insert into keyword (name) values ('Música');
insert into keyword (name) values ('Teatro');
insert into keyword (name) values ('Cinema');
insert into keyword (name) values ('Literatura');
insert into keyword (name) values ('Exposição');
insert into keyword (name) values ('Museu');
insert into keyword (name) values ('Património');
insert into keyword (name) values ('Monumento');
insert into keyword (name) values ('Castelo');
insert into keyword (name) values ('Igreja');
insert into keyword (name) values ('Catedral');
insert into keyword (name) values ('Mosteiro');
insert into keyword (name) values ('Ruína');
insert into keyword (name) values ('Arqueologia');
insert into keyword (name) values ('Arqueólogo');
insert into keyword (name) values ('Descoberta');
insert into keyword (name) values ('Crítica');
insert into keyword (name) values ('Opinião');
insert into keyword (name) values ('Editorial');
insert into keyword (name) values ('Notícia');
insert into keyword (name) values ('Reportagem');
insert into keyword (name) values ('Entrevista');
insert into keyword (name) values ('Artigo');
insert into keyword (name) values ('Opinião Pública');
insert into keyword (name) values ('Opinião Política');
insert into keyword (name) values ('Analista');
insert into keyword (name) values ('Colunista');
insert into keyword (name) values ('Comentador');
insert into keyword (name) values ('Sociedade');
insert into keyword (name) values ('Democracia');
insert into keyword (name) values ('Direitos Civis');
insert into keyword (name) values ('Direitos Sociais');
insert into keyword (name) values ('Liberdade');
insert into keyword (name) values ('Igualdade');
insert into keyword (name) values ('Fraternidade');
insert into keyword (name) values ('Justiça Social');
insert into keyword (name) values ('Igualdade de Género');
insert into keyword (name) values ('Políticas Públicas');
insert into keyword (name) values ('Legislação');
insert into keyword (name) values ('Regulamentação');
insert into keyword (name) values ('Constituição');
insert into keyword (name) values ('Código Civil');
insert into keyword (name) values ('Código Penal');
insert into keyword (name) values ('Lei');
insert into keyword (name) values ('Decreto');
insert into keyword (name) values ('Portaria');
insert into keyword (name) values ('Despacho');
insert into keyword (name) values ('Regulamento');
insert into keyword (name) values ('Orçamento');
insert into keyword (name) values ('Tribunal Constitucional');
insert into keyword (name) values ('Supremo Tribunal');
insert into keyword (name) values ('Câmara Legislativa');
insert into keyword (name) values ('Deputado');
insert into keyword (name) values ('Senador');
insert into keyword (name) values ('Ministro');
insert into keyword (name) values ('Secretário de Estado');
insert into keyword (name) values ('Presidente da República');
insert into keyword (name) values ('Presidente do Governo');
insert into keyword (name) values ('Secretário Geral');
insert into keyword (name) values ('Embaixada');
insert into keyword (name) values ('Consulado');
insert into keyword (name) values ('Polícia Judiciária');
insert into keyword (name) values ('GNR');
insert into keyword (name) values ('PSP');
insert into keyword (name) values ('Segurança Social');
insert into keyword (name) values ('Saúde Pública');
insert into keyword (name) values ('Hospitais');
insert into keyword (name) values ('Clínicas');
insert into keyword (name) values ('Médicos');
insert into keyword (name) values ('Enfermeiros');
insert into keyword (name) values ('Vacinas');
insert into keyword (name) values ('Doença');
insert into keyword (name) values ('Pandemia');
insert into keyword (name) values ('Tratamento');
insert into keyword (name) values ('Investigação Médica');
insert into keyword (name) values ('Biotecnologia');
insert into keyword (name) values ('Fármacos');
insert into keyword (name) values ('Farmácia');
insert into keyword (name) values ('Saúde Mental');
insert into keyword (name) values ('Psiquiatria');
insert into keyword (name) values ('Psicologia');
insert into keyword (name) values ('Prevenção');
insert into keyword (name) values ('Imunização');
insert into keyword (name) values ('Assistência Social');
insert into keyword (name) values ('Segurança Alimentar');
insert into keyword (name) values ('Meio Ambiente');
insert into keyword (name) values ('Poluição');
insert into keyword (name) values ('Desflorestação');
insert into keyword (name) values ('Recursos Naturais');
insert into keyword (name) values ('Renováveis');
insert into keyword (name) values ('Energia Solar');
insert into keyword (name) values ('Energia Eólica');
insert into keyword (name) values ('Transporte Público');
insert into keyword (name) values ('Metro');
insert into keyword (name) values ('Comboio');
insert into keyword (name) values ('Aeroporto');
insert into keyword (name) values ('Porto Marítimo');
insert into keyword (name) values ('Navios');
insert into keyword (name) values ('Marinha');
insert into keyword (name) values ('Exército');
insert into keyword (name) values ('Defesa Nacional');
insert into keyword (name) values ('Segurança Interna');
insert into keyword (name) values ('Redes Informáticas');
insert into keyword (name) values ('Proteção de Dados');
insert into keyword (name) values ('Internet das Coisas');
insert into keyword (name) values ('Machine Learning');
insert into keyword (name) values ('Robótica');
insert into keyword (name) values ('Automação');
insert into keyword (name) values ('Criptomoeda');
insert into keyword (name) values ('Bitcoin');
insert into keyword (name) values ('Ethereum');
insert into keyword (name) values ('Finanças');
insert into keyword (name) values ('Crise Financeira');
insert into keyword (name) values ('Salário');
insert into keyword (name) values ('Subsídio');
insert into keyword (name) values ('Imposto');
insert into keyword (name) values ('Proteção Social');
insert into keyword (name) values ('Ensino Superior');
insert into keyword (name) values ('Faculdade');
insert into keyword (name) values ('Instituto Politécnico');
insert into keyword (name) values ('Artes');
insert into keyword (name) values ('Ruínas');
insert into keyword (name) values ('Coluna');
insert into keyword (name) values ('Promotor');
insert into keyword (name) values ('Processo Judicial');
insert into keyword (name) values ('Audiência');
insert into keyword (name) values ('Sentença');
insert into keyword (name) values ('Apelação');
insert into keyword (name) values ('Correios');
insert into keyword (name) values ('Transportes');
insert into keyword (name) values ('Logística');
insert into keyword (name) values ('Comércio');
insert into keyword (name) values ('Indústria');
insert into keyword (name) values ('Empresas');
insert into keyword (name) values ('Bolsa de Valores');
insert into keyword (name) values ('Investimento Público');
insert into keyword (name) values ('Investimento Privado');
insert into keyword (name) values ('Exportação');
insert into keyword (name) values ('Importação');
insert into keyword (name) values ('Comércio Internacional');
insert into keyword (name) values ('Hotelaria');
insert into keyword (name) values ('Restaurantes');
insert into keyword (name) values ('Eventos');
insert into keyword (name) values ('Cultura Pop');
insert into keyword (name) values ('Andebol');
insert into keyword (name) values ('Basquetebol');
insert into keyword (name) values ('Atletismo');
insert into keyword (name) values ('Natação');
insert into keyword (name) values ('Ciclismo');
insert into keyword (name) values ('Surf');
insert into keyword (name) values ('Desporto Escolar');
insert into keyword (name) values ('Clubes');
insert into keyword (name) values ('Seleções');
insert into keyword (name) values ('Jogos Olímpicos');
insert into keyword (name) values ('Jogos Europeus');
insert into keyword (name) values ('Jogos Mundiais');
insert into keyword (name) values ('Alimentação');
insert into keyword (name) values ('Nutrição');
insert into keyword (name) values ('Desenvolvimento Sustentável');
insert into keyword (name) values ('Clima');
insert into keyword (name) values ('Alterações Climáticas');
insert into keyword (name) values ('Recursos Hídricos');
insert into keyword (name) values ('Reciclagem');
insert into keyword (name) values ('Lixo');
insert into keyword (name) values ('Poluição do Ar');
insert into keyword (name) values ('Poluição da Água');
insert into keyword (name) values ('Conservação');
insert into keyword (name) values ('Parques Naturais');
insert into keyword (name) values ('Reserva Natural');
insert into keyword (name) values ('Proteção Animal');
insert into keyword (name) values ('ONG');
insert into keyword (name) values ('Fundação');
insert into keyword (name) values ('Voluntariado');
insert into keyword (name) values ('Projetos Sociais');
insert into keyword (name) values ('Iniciativa Privada');
insert into keyword (name) values ('Inovação Social');
insert into keyword (name) values ('Empreendedorismo Social');
insert into keyword (name) values ('Startups Sociais');
insert into keyword (name) values ('Marketing Digital');
insert into keyword (name) values ('Privacidade Online');
insert into keyword (name) values ('Cibercrime');
insert into keyword (name) values ('Segurança Digital');
insert into keyword (name) values ('Aplicações Móveis');
insert into keyword (name) values ('Software');
insert into keyword (name) values ('Hardware');
insert into keyword (name) values ('Fintech');
insert into keyword (name) values ('Bancos');
insert into keyword (name) values ('Seguros');
insert into keyword (name) values ('Investimentos');
insert into keyword (name) values ('Arte');
insert into keyword (name) values ('Design');
insert into keyword (name) values ('Arquitetura');
insert into keyword (name) values ('Urbanismo');
insert into keyword (name) values ('Planeamento Urbano');
insert into keyword (name) values ('Habitação');
insert into keyword (name) values ('Infraestrutura');
insert into keyword (name) values ('Transportes Públicos');
insert into keyword (name) values ('Comboios');
insert into keyword (name) values ('Portos');
insert into keyword (name) values ('Distribuição');
insert into keyword (name) values ('Economia Digital');
insert into keyword (name) values ('Instituto');
insert into keyword (name) values ('Medicina');
insert into keyword (name) values ('Vacina');
insert into keyword (name) values ('Hospital');
insert into keyword (name) values ('Clínica');