insert into keyword (name) values ('Adalberto Campos Fernandes');
insert into keyword (name) values ('Adelino Amaro da Costa');
insert into keyword (name) values ('Adelino da Palma Carlos');
insert into keyword (name) values ('Adolfo Mesquita Nunes');
insert into keyword (name) values ('Adérito Sedas Nunes');
insert into keyword (name) values ('Alberto Costa');
insert into keyword (name) values ('Alberto Martins');
insert into keyword (name) values ('Alberto Oliveira e Silva');
insert into keyword (name) values ('Alberto Ralha');
insert into keyword (name) values ('Alberto Santos');
insert into keyword (name) values ('Alexandra Leitão');
insert into keyword (name) values ('Alexandra Reis');
insert into keyword (name) values ('Alexandre Homem Cristo');
insert into keyword (name) values ('Alfredo César Torres');
insert into keyword (name) values ('Alfredo Nobre da Costa');
insert into keyword (name) values ('Ana Abrunhosa');
insert into keyword (name) values ('Ana Benavente');
insert into keyword (name) values ('Ana Catarina Mendes');
insert into keyword (name) values ('Ana Fontoura Gouveia');
insert into keyword (name) values ('Ana Jorge');
insert into keyword (name) values ('Ana Mendes Godinho');
insert into keyword (name) values ('Ana Paula Vitorino');
insert into keyword (name) values ('Ana Sofia Antunes');
insert into keyword (name) values ('Anabela Rodrigues');
insert into keyword (name) values ('André Gonçalves Pereira');
insert into keyword (name) values ('André Moz Caldas');
insert into keyword (name) values ('António Cardoso e Cunha');
insert into keyword (name) values ('António Carlos de Magalhães Arnao Metello');
insert into keyword (name) values ('António Coimbra Martins');
insert into keyword (name) values ('António Correia de Campos');
insert into keyword (name) values ('António Costa');
insert into keyword (name) values ('António Costa Silva');
insert into keyword (name) values ('António Couto dos Santos');
insert into keyword (name) values ('António Figueiredo Lopes');
insert into keyword (name) values ('António Gonçalves Ribeiro');
insert into keyword (name) values ('António Guterres');
insert into keyword (name) values ('António Leite');
insert into keyword (name) values ('António Maldonado Gonelha');
insert into keyword (name) values ('António Martins da Cruz');
insert into keyword (name) values ('António Mendonça Mendes');
insert into keyword (name) values ('António Monteiro');
insert into keyword (name) values ('António Vitorino');
insert into keyword (name) values ('António de Almeida Santos');
insert into keyword (name) values ('António do Carmo Galhordas');
insert into keyword (name) values ('Aníbal Cavaco Silva');
insert into keyword (name) values ('Arlindo de Carvalho');
insert into keyword (name) values ('Artur Santos Silva');
insert into keyword (name) values ('Augusto Santos Silva');
insert into keyword (name) values ('Bernardo Ivo Cruz');
insert into keyword (name) values ('Bernardo Trindade');
insert into keyword (name) values ('Berta Nunes');
insert into keyword (name) values ('Carlos Alberto Lloyd Braga');
insert into keyword (name) values ('Carlos Corrêa Gago');
insert into keyword (name) values ('Carlos Manuel Soares Miguel');
insert into keyword (name) values ('Carlos Melancia');
insert into keyword (name) values ('Carlos Mota Pinto');
insert into keyword (name) values ('Carlos Pimenta');
insert into keyword (name) values ('Carlos da Costa Neves');
insert into keyword (name) values ('Carlos de Brito');
insert into keyword (name) values ('Catarina Sarmento e Castro');
insert into keyword (name) values ('Catarina Vaz Pinto');
insert into keyword (name) values ('Cecília Meireles');
insert into keyword (name) values ('Celeste Cardona');
insert into keyword (name) values ('Constança Urbano de Sousa');
insert into keyword (name) values ('Coriolano Albino Ferreira');
insert into keyword (name) values ('Dalila Rodrigues');
insert into keyword (name) values ('Dan Katz');
insert into keyword (name) values ('Daniel Proença de Carvalho');
insert into keyword (name) values ('Daniel Sanches');
insert into keyword (name) values ('David Justino');
insert into keyword (name) values ('Diamantino Durão');
insert into keyword (name) values ('Diogo Freitas do Amaral');
insert into keyword (name) values ('Duarte Cordeiro');
insert into keyword (name) values ('Eduardo Cabrita');
insert into keyword (name) values ('Eduardo Catroga');
insert into keyword (name) values ('Eduardo Ferro Rodrigues');
insert into keyword (name) values ('Eduardo Pereira');
insert into keyword (name) values ('Eduardo Pinheiro');
insert into keyword (name) values ('Eduardo Silva Correia');
insert into keyword (name) values ('Elisa Ferreira');
insert into keyword (name) values ('Elvira Fortunato');
insert into keyword (name) values ('Elza Pais');
insert into keyword (name) values ('Ernesto Melo Antunes');
insert into keyword (name) values ('Fernando Gomes');
insert into keyword (name) values ('Fernando Leal da Costa');
insert into keyword (name) values ('Fernando Medina');
insert into keyword (name) values ('Fernando Negrão');
insert into keyword (name) values ('Fernando Nogueira');
insert into keyword (name) values ('Fernando Teixeira dos Santos');
insert into keyword (name) values ('Fernando do Amaral');
insert into keyword (name) values ('Francisca Van Dunem');
insert into keyword (name) values ('Francisco André');
insert into keyword (name) values ('Francisco José Viegas');
insert into keyword (name) values ('Francisco Lucas Pires');
insert into keyword (name) values ('Francisco Luís Murteira Nabo');
insert into keyword (name) values ('Francisco Pinto Balsemão');
insert into keyword (name) values ('Francisco Salgado Zenha');
insert into keyword (name) values ('Francisco Seixas da Costa');
insert into keyword (name) values ('Francisco Sá Carneiro');
insert into keyword (name) values ('Gabriel Bastos');
insert into keyword (name) values ('Gabriela Canavilhas');
insert into keyword (name) values ('Graça Fonseca');
insert into keyword (name) values ('Guilherme d'Oliveira Martins');
insert into keyword (name) values ('Helena Carreiras');
insert into keyword (name) values ('Helena Ribeiro');
insert into keyword (name) values ('Henrique José Monteiro Santa Clara Gomes');
insert into keyword (name) values ('Henrique Medina Carreira');
insert into keyword (name) values ('Henrique de Freitas');
insert into keyword (name) values ('Henrique de Oliveira Constantino');
insert into keyword (name) values ('Hernâni Dias');
insert into keyword (name) values ('Hugo Santos Mendes');
insert into keyword (name) values ('Humberto Rosa');
insert into keyword (name) values ('Inês Domingos');
insert into keyword (name) values ('Inês Ramires');
insert into keyword (name) values ('Isabel Alçada');
insert into keyword (name) values ('Isabel Cordeiro');
insert into keyword (name) values ('Isabel Oneto');
insert into keyword (name) values ('Isabel Rodrigues');
insert into keyword (name) values ('Isaltino Morais');
insert into keyword (name) values ('Jaime Gama');
insert into keyword (name) values ('Joaquim Ferreira do Amaral');
insert into keyword (name) values ('Joaquim Magalhães Mota');
insert into keyword (name) values ('Joaquim Rocha e Cunha');
insert into keyword (name) values ('Jorge Alves Costa');
insert into keyword (name) values ('Jorge Barreto Xavier');
insert into keyword (name) values ('Jorge Braga de Macedo');
insert into keyword (name) values ('Jorge Campinos');
insert into keyword (name) values ('Jorge Correia Jesuíno');
insert into keyword (name) values ('Jorge Delgado');
insert into keyword (name) values ('Jorge Nogueiro Gomes');
insert into keyword (name) values ('José Alberto Azeredo Lopes');
insert into keyword (name) values ('José Apolinário');
insert into keyword (name) values ('José Falcão e Cunha');
insert into keyword (name) values ('José Fernando Gomes Mendes');
insert into keyword (name) values ('José Luís Carneiro');
insert into keyword (name) values ('José Luís Lopes da Mota');
insert into keyword (name) values ('José Manuel Durão Barroso');
insert into keyword (name) values ('José Manuel Sérvulo Correia');
insert into keyword (name) values ('José Maria Costa');
insert into keyword (name) values ('José Menéres Pimentel');
insert into keyword (name) values ('José Pedro Aguiar Branco');
insert into keyword (name) values ('José Pinheiro de Azevedo');
insert into keyword (name) values ('José Pinto Ribeiro');
insert into keyword (name) values ('José Santos Pais');
insert into keyword (name) values ('José Sasportes');
insert into keyword (name) values ('José Silveira Godinho');
insert into keyword (name) values ('José Sócrates');
insert into keyword (name) values ('José Teixeira Ribeiro');
insert into keyword (name) values ('José Veiga Simão');
insert into keyword (name) values ('José Vera Jardim');
insert into keyword (name) values ('José da Silva Lopes');
insert into keyword (name) values ('João António Lopes da Conceição');
insert into keyword (name) values ('João Ataíde das Neves');
insert into keyword (name) values ('João Barroso Soares');
insert into keyword (name) values ('João Calvão da Silva');
insert into keyword (name) values ('João Costa');
insert into keyword (name) values ('João Filipe Queiró');
insert into keyword (name) values ('João Galamba');
insert into keyword (name) values ('João Gomes Cravinho');
insert into keyword (name) values ('João Leão');
insert into keyword (name) values ('João Menezes Ferreira');
insert into keyword (name) values ('João Neves');
insert into keyword (name) values ('João Nuno Mendes');
insert into keyword (name) values ('João Paulo Catarino');
insert into keyword (name) values ('João Paulo Correia');
insert into keyword (name) values ('João Pedro Matos Fernandes');
insert into keyword (name) values ('João Salgueiro');
insert into keyword (name) values ('João Vieira Lima');
insert into keyword (name) values ('João Wengorovius Meneses');
insert into keyword (name) values ('João de Deus Pinheiro');
insert into keyword (name) values ('João de Deus Pinheiro Farinha');
insert into keyword (name) values ('João de Freitas Branco');
insert into keyword (name) values ('Júlio Castro Caldas');
insert into keyword (name) values ('Leonardo Ribeiro de Almeida');
insert into keyword (name) values ('Leonor Beleza');
insert into keyword (name) values ('Loureiro dos Santos');
insert into keyword (name) values ('Luís Amado');
insert into keyword (name) values ('Luís Campos e Cunha');
insert into keyword (name) values ('Luís Capoulas Santos');
insert into keyword (name) values ('Luís Filipe Castro Mendes');
insert into keyword (name) values ('Luís Filipe Madeira');
insert into keyword (name) values ('Luís Filipe Pereira');
insert into keyword (name) values ('Luís Manuel Vítor dos Santos Moita');
insert into keyword (name) values ('Luís Marques Guedes');
insert into keyword (name) values ('Luís Marques Mendes');
insert into keyword (name) values ('Luís Medeiros Vieira');
insert into keyword (name) values ('Luís Montenegro');
insert into keyword (name) values ('Luís Nandim de Carvalho');
insert into keyword (name) values ('Luís Patrão');
insert into keyword (name) values ('Luís Veiga da Cunha');
insert into keyword (name) values ('Luís de Azevedo Coutinho');
insert into keyword (name) values ('Lídia Bulcão');
insert into keyword (name) values ('Manuel Dias Loureiro');
insert into keyword (name) values ('Manuel Gomes Guerreiro');
insert into keyword (name) values ('Manuel Heitor');
insert into keyword (name) values ('Manuel Pereira');
insert into keyword (name) values ('Manuel Pizarro');
insert into keyword (name) values ('Manuel da Costa Braz');
insert into keyword (name) values ('Manuela Arcanjo');
insert into keyword (name) values ('Manuela Ferreira Leite');
insert into keyword (name) values ('Marcelo Rebelo de Sousa');
insert into keyword (name) values ('Marcelo de Sousa Vasconcelos');
insert into keyword (name) values ('Marco Capitão Ferreira');
insert into keyword (name) values ('Margarida Mano');
insert into keyword (name) values ('Maria João Rodrigues');
insert into keyword (name) values ('Maria Luís Albuquerque');
insert into keyword (name) values ('Maria de Belém Roseira');
insert into keyword (name) values ('Maria de Lourdes Pintasilgo');
insert into keyword (name) values ('Maria de Lurdes Rodrigues');
insert into keyword (name) values ('Maria do Carmo Seabra');
insert into keyword (name) values ('Maria do Céu Antunes');
insert into keyword (name) values ('Maria do Rosário Palma Ramalho');
insert into keyword (name) values ('Mariana Vieira da Silva');
insert into keyword (name) values ('Mariano Gago');
insert into keyword (name) values ('Marina Gonçalves');
insert into keyword (name) values ('Marta Temido');
insert into keyword (name) values ('Marçal Grilo');
insert into keyword (name) values ('Miguel Alves');
insert into keyword (name) values ('Miguel Beleza');
insert into keyword (name) values ('Miguel Cadilhe');
insert into keyword (name) values ('Miguel Fontes');
insert into keyword (name) values ('Miguel Macedo');
insert into keyword (name) values ('Miguel Prata Roque');
insert into keyword (name) values ('Miguel Relvas');
insert into keyword (name) values ('Mário Campolargo');
insert into keyword (name) values ('Mário Centeno');
insert into keyword (name) values ('Mário Firmino Miguel');
insert into keyword (name) values ('Mário Neves');
insert into keyword (name) values ('Mário Raposo');
insert into keyword (name) values ('Mário Ruivo');
insert into keyword (name) values ('Mário Soares');
insert into keyword (name) values ('Nelson de Souza');
insert into keyword (name) values ('Nuno Crato');
insert into keyword (name) values ('Nuno Fazenda');
insert into keyword (name) values ('Nuno Félix');
insert into keyword (name) values ('Nuno Severiano Teixeira');
insert into keyword (name) values ('Patrícia Gaspar');
insert into keyword (name) values ('Paula Teixeira da Cruz');
insert into keyword (name) values ('Paulo Cafôfo');
insert into keyword (name) values ('Paulo Macedo');
insert into keyword (name) values ('Paulo Mendo');
insert into keyword (name) values ('Paulo Portas');
insert into keyword (name) values ('Paulo Rangel');
insert into keyword (name) values ('Paulo Teixeira Pinto');
insert into keyword (name) values ('Pedro Adão e Silva');
insert into keyword (name) values ('Pedro Cilínio');
insert into keyword (name) values ('Pedro Duarte');
insert into keyword (name) values ('Pedro Nuno Santos');
insert into keyword (name) values ('Pedro Nuno Teixeira');
insert into keyword (name) values ('Pedro Passos Coelho');
insert into keyword (name) values ('Pedro Pires de Miranda');
insert into keyword (name) values ('Pedro Santana Lopes');
insert into keyword (name) values ('Pedro Silva Pereira');
insert into keyword (name) values ('Pedro Siza Vieira');
insert into keyword (name) values ('Pedro Sousa Macedo');
insert into keyword (name) values ('Pedro Tavares');
insert into keyword (name) values ('Ricardo Mestre');
insert into keyword (name) values ('Ricardo Pinheiro');
insert into keyword (name) values ('Ricardo Serrão Santos');
insert into keyword (name) values ('Rita Júdice');
insert into keyword (name) values ('Rita Marques');
insert into keyword (name) values ('Roberto Carneiro');
insert into keyword (name) values ('Rui Amaral');
insert into keyword (name) values ('Rui Machete');
insert into keyword (name) values ('Rui Martinho');
insert into keyword (name) values ('Rui Pena');
insert into keyword (name) values ('Rui Pereira');
insert into keyword (name) values ('Silvano Ribeiro');
insert into keyword (name) values ('Sofia Batalha');
insert into keyword (name) values ('Sofia Galvão');
insert into keyword (name) values ('Susana Amador');
insert into keyword (name) values ('Teresa Coelho');
insert into keyword (name) values ('Teresa Morais');
insert into keyword (name) values ('Teresa Patrício Gouveia');
insert into keyword (name) values ('Tiago Antunes');
insert into keyword (name) values ('Tiago Brandão Rodrigues');
insert into keyword (name) values ('Vasco Almeida e Costa');
insert into keyword (name) values ('Vasco Gonçalves');
insert into keyword (name) values ('Vasco Pulido Valente');
insert into keyword (name) values ('Victor de Sá Machado');
insert into keyword (name) values ('Vítor Alves');
insert into keyword (name) values ('Vítor Barros');
insert into keyword (name) values ('Vítor Cabrita Neto');
insert into keyword (name) values ('Vítor Constâncio');
insert into keyword (name) values ('Álvaro Cunhal');
insert into keyword (name) values ('Álvaro Laborinho Lúcio');
insert into keyword (name) values ('Álvaro Veiga de Oliveira');
insert into keyword (name) values ('Ângela Ferreira');
insert into keyword (name) values ('Ângelo Correia');