insert into person (name) values ('António Ramalho Eanes');
insert into person (name) values ('Otelo Saraiva de Carvalho');
insert into person (name) values ('José Pinheiro de Azevedo');
insert into person (name) values ('Octávio Pato');
insert into person (name) values ('António Soares Carneiro');
insert into person (name) values ('Carlos Galvão de Melo');
insert into person (name) values ('António Pires Veloso');
insert into person (name) values ('António Aires Rodrigues');
insert into person (name) values ('Mário Soares');
insert into person (name) values ('Diogo Freitas do Amaral');
insert into person (name) values ('Carlos Marques');
insert into person (name) values ('Maria de Lurdes Pintasilgo');
insert into person (name) values ('Basílio Horta');
insert into person (name) values ('Carlos Carvalhas');
insert into person (name) values ('Jorge Sampaio');
insert into person (name) values ('Aníbal Cavaco Silva');
insert into person (name) values ('Alberto Matos');
insert into person (name) values ('Fernando Rosas');
insert into person (name) values ('António Garcia Pereira');
insert into person (name) values ('António Abreu');
insert into person (name) values ('Fernando Nobre');
insert into person (name) values ('Manuel Alegre');
insert into person (name) values ('Francisco Lopes');
insert into person (name) values ('Defensor Moura');
insert into person (name) values ('Vitorino Silva');
insert into person (name) values ('Marcelo Rebelo de Sousa');
insert into person (name) values ('António Sampaio da Nóvoa');
insert into person (name) values ('Marisa Matias');
insert into person (name) values ('Maria de Belém Roseira');
insert into person (name) values ('Edgar Silva');
insert into person (name) values ('Paulo de Morais');
insert into person (name) values ('Henrique Neto');
insert into person (name) values ('Ana Gomes');
insert into person (name) values ('André Ventura');
insert into person (name) values ('João Ferreira');
insert into person (name) values ('Tiago Mayan Gonçalves');
insert into person (name) values ('Manuel João Vieira');
insert into person (name) values ('João Cotrim de Figueiredo');
insert into person (name) values ('Henrique Gouveia e Melo');
insert into person (name) values ('Luís Marques Mendes');
insert into person (name) values ('Catarina Martins');
insert into person (name) values ('António Filipe');
insert into person (name) values ('André Pestana');
insert into person (name) values ('Humberto Correia');
insert into person (name) values ('Jorge Pinto');