insert into person (name) values ('António Arnaut');
insert into person (name) values ('Manuel Tito de Morais');
insert into person (name) values ('António Reis');
insert into person (name) values ('José Medeiros Ferreira');
insert into person (name) values ('Jaime Gama');
insert into person (name) values ('Guilherme Silva');
insert into person (name) values ('Pacheco Pereira');
insert into person (name) values ('Luís Marques Guedes');
insert into person (name) values ('António Capucho');
insert into person (name) values ('Manuel Moreira');
insert into person (name) values ('José Lello');
insert into person (name) values ('António Braga');
insert into person (name) values ('Alberto João Jardim');
insert into person (name) values ('José Junqueiro');
insert into person (name) values ('Sérgio Sousa Pinto');
insert into person (name) values ('António Gameiro');
insert into person (name) values ('Ricardo Rodrigues');
insert into person (name) values ('José Moura Soeiro');
insert into person (name) values ('Heitor Sousa');
insert into person (name) values ('João Semedo');
-- already in 007-party-leaders.sql: insert into person (name) values ('Luís Montenegro');
insert into person (name) values ('Miguel Relvas');
insert into person (name) values ('António Leitão Amaro');
insert into person (name) values ('Carlos Abreu Amorim');
insert into person (name) values ('Teresa Leal Coelho');
insert into person (name) values ('Miguel Macedo');
insert into person (name) values ('José Manuel Fernandes');
insert into person (name) values ('Pedro Mota Soares');
insert into person (name) values ('Nuno Magalhães');
insert into person (name) values ('João Almeida');
insert into person (name) values ('Rui Paulo Figueiredo');
insert into person (name) values ('Jorge Costa');
insert into person (name) values ('José Luís Ferreira');
insert into person (name) values ('António Costa Silva');
insert into person (name) values ('Luís Testa');
insert into person (name) values ('Ana Paula Vitorino');
insert into person (name) values ('Ascenso Simões');
-- already in 006-president-candidates-data.sql: insert into person (name) values ('Ana Gomes');
insert into person (name) values ('José Luís Arnaut');
insert into person (name) values ('Fernando Serrasqueiro');
insert into person (name) values ('Paulo Rangel');
insert into person (name) values ('Carlos Coelho');
insert into person (name) values ('António Montalvão Machado');
-- already in 007-party-leaders.sql: insert into person (name) values ('Luís Fazenda');
insert into person (name) values ('Odete Santos');
-- already in 006-president-candidates-data.sql: insert into person (name) values ('António Filipe');
insert into person (name) values ('Honório Novo');
insert into person (name) values ('Bernardino Soares');
insert into person (name) values ('Rita Rato');
insert into person (name) values ('João Oliveira');
insert into person (name) values ('Hugo Velosa');
insert into person (name) values ('José Cesário');
insert into person (name) values ('Carlos César');
insert into person (name) values ('Ana Catarina Mendes');
insert into person (name) values ('Pedro Delgado Alves');
insert into person (name) values ('Isabel Moreira');
insert into person (name) values ('Fernando Negrão');
insert into person (name) values ('Duarte Pacheco');
insert into person (name) values ('Adão Silva');
insert into person (name) values ('Pedro Filipe Soares');
-- already in 007-party-leaders.sql: insert into person (name) values ('Mariana Mortágua');
insert into person (name) values ('Inês Sousa Real');
-- already in 007-party-leaders.sql: insert into person (name) values ('Rui Tavares');
-- already in 006-president-candidates-data.sql: insert into person (name) values ('João Cotrim de Figueiredo');
-- already in 007-party-leaders.sql: insert into person (name) values ('Rui Rocha');
-- already in 006-president-candidates-data.sql: insert into person (name) values ('André Ventura');
insert into person (name) values ('Pedro Pinto');
insert into person (name) values ('Rita Matias');
insert into person (name) values ('Alexandre Poço');