# Spring server
server.port=8080

# Postgres
spring.datasource.url=jdbc:postgresql://localhost/scribe-ref-db
spring.datasource.username=postgres
spring.datasource.password=postgres

#Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.acks=all
spring.kafka.properties.allow.auto.create.topics=true
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

## topic to send
scribe-ref.arquivo.scribe-news-crawler.kafka.to-send.topic=arquivo-response-items
scribe-ref.arquivo.scribe-news-crawler.kafka.to-send.concurrency=1

# Service properties
scribe-ref.arquivo.scribe-news-crawler.enable=true

